### ISSUE TITLE
packer compile autocmd is too crude

### ISSUE THREAD

**Issue by jdhao** [Integralist/dotfiles#2]
The autocmd defined [here](https://github.com/Integralist/dotfiles/blob/0cded8acafbbd5845c19f1c3979c44aa99cb23a7/.config/nvim/lua/plugin-manager.lua#L24) is too crude.

It will fire for every lua file. Is this really what you want? You should at least restrict the pattern used to be more specific.

**Comment by Integralist** [comment]
Yup. I jump around and modify lots of files and like to recompile for any changed files.

**Comment by Integralist** [comment]
Oh well, it's not causing me any problems at the moment so I can live with it. Thanks for raising this though 👍
